# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "docker" do |docker|
		docker.vm.box = "bento/centos-7.2"
		docker.vm.hostname = "docker-runner"
		docker.vm.network "private_network", ip: "192.168.50.10"
		
		docker.vm.synced_folder "E:/dev/checkout/AutomationSandbox/Docker", "/docker/"
	end
	
#	config.vm.define "web" do |web|
#		web.vm.box = "nrel/CentOS-6.5-x86_64"
#		web.vm.hostname = "web"
#		web.vm.network "private_network", ip: "192.168.33.20"
#		web.vm.network "forwarded_port", guest: 80, host: 1972
#	end

#	config.vm.define "db" do |db|
#		db.vm.box = "nrel/CentOS-6.5-x86_64"
#		db.vm.hostname = "db"
#		db.vm.network "private_network", ip: "192.168.33.30"
#	end

end
